var Product = require('../models/product');
var mongoose = require('mongoose');
//mongoose.connect('mongodb://localhost/shopping')
mongoose.connect('mongodb+srv://admin:adminpassword@tanhung-o7d5l.mongodb.net/shopping?retryWrites=true&w=majority', { useUnifiedTopology: true});

var products = [new Product({
    IDSTall:"5e12178b6fbe5b1648551e94",
    imagePath: "/img/product01.jpg",
    linkproduct: "tui_nu_vn135",
    productname: "Túi xách nữ màu Đen VN135",
    saleoff: "-20%",
    price: 179500,
    oldprice: 200500,
    cat: "Cặp",
    producer: "vanoca",
    availability: "có",
    description: "Chất liệu da cao cấp.Thiết kế trẻ trung, sang trọng, lịch sự.Đường chỉ may, tỉ mỉ, đẹp mắt.",
    gender: "nữ"
}),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/product02.jpg",
        linkproduct: "dong_ho_nam_dz66",
        productname: "(Mẫu HOT 2019) Đồng hồ nam chính hãng DZ66",
        saleoff: "-15%",
        price: 229000,
        oldprice: 250500,
        cat: "Đồng hồ",
        producer: "manzo",
        availability: "có",
        description: "Tinh tế và luôn là nguồn cảm hứng bất tận trong giới thời trang, chiếc đồng hồ nam mạnh mẽ và thật nổi bật trên cổ tay của nam giới.",
        gender: "nam",

    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/product03.jpg",
        linkproduct: "vi_nam_da_bo",
        productname: "Ví nam da bò thật 100% cao cấp",
        saleoff: "-5%",
        price: 199000,
        oldprice: 210000,
        cat: "Ví",
        producer: "manzo",
        availability: "có",
        description: "Ví MANZO VN28.V được làm bằng da bò cao cấp, ví có 3 ngăn lớn ( 1 ngăn có khóa) và có rất nhiều ngăn nhỏ có thể có thể đựng vừa vừa các loại giấy tờ",
        gender: "nam"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/product04.jpg",
        linkproduct: "giay_sneakers_gv01",
        productname: "Giày Vải Sneakers - Pettino GV01",
        saleoff: "-15%",
        price: 80000,
        oldprice: 100000,
        cat: "Giày",
        producer: "manzo",
        availability: "có",
        description: "Công nghệ EVOFIT giúp bạn leo núi cực kỳ thoải mái. Tấm chắn đá văng bằng cao su, phần thân trên bằng da, màng chống thấm nước và đế lót bám để leo núi",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/product05.jpg",
        linkproduct: "ung_bao_ho_ss1065",
        productname: "Ủng bảo hộ lao động Thùy Dương mũi và đế thép SS1065",
        saleoff: "-25%",
        price: 300000,
        oldprice: 400000,
        cat: "Giày",
        producer: "manzo",
        availability: "có",
        description: "Hercules S5 Kích cỡ: Size EU 36-47/ US 6-13 / UK 3.5-12 Chất liệu: Đế được làm bằng chất liệu PVC, mũi thép.",
        gender: "nữ"
    }),

    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/Apple01.jpg",
        linkproduct: "dong_ho_apple_den",
        productname: "Đồng hồ thông minh Apple màu đen",
        saleoff: "-10%",
        price: 3200000,
        oldprice: 3520000,
        cat: "Đồng hồ",
        producer: "apple",
        availability: "có",
        description: "Một chiếc đồng hồ rất nhiều tính năng thông minh, quan tâm đến sức khỏe và là món đồ trang sức tuyệt đẹp",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/Apple02.jpg",
        linkproduct: "dong_ho_apple_anh_kim",
        productname: "Đồng hồ thông minh Apple màu ánh kim",
        saleoff: "-10%",
        price: 2700000,
        oldprice: 3000000,
        cat: "Đồng hồ",
        producer: "apple",
        availability: "có",
        description: "Tính năng nổi bật như đo nhịp tim và huyết áp, chống nước,... Ưu đãi khủng. Giá đặc biệt hôm nay. Mua ngay.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/Apple03.png",
        linkproduct: "dong_ho_apple_trang",
        productname: "Đồng hồ thông minh Apple màu trắng",
        saleoff: "-20%",
        price: 2800000,
        oldprice: 3500000,
        cat: "Đồng hồ",
        producer: "apple",
        availability: "có",
        description: "Là một trong những chiếc đồng hồ thông minh tốt nhất hiện nay với nhiều tính năng nổi bật như ECG (điện tâm đồ).",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/Apple04.png",
        linkproduct: "dong_ho_apple_huong",
        productname: "Đồng hồ thông minh Apple màu hường",
        saleoff: "-10%",
        price: 2700000,
        oldprice: 3000000,
        cat: "Đồng hồ",
        producer: "apple",
        availability: "có",
        description: "Một chiếc đồng hồ rất nhiều tính năng thông minh, quan tâm đến sức khỏe và là món đồ trang sức tuyệt đẹp.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/Samsung_Galaxy_SM_R800.jpg",
        linkproduct: "dong_ho_samsung_sm_r800",
        productname: "Đồng hồ thông minh Samsung Galaxy SM-R800",
        saleoff: "-10%",
        price: 5400000,
        oldprice: 6000000,
        cat: "Đồng hồ",
        producer: "samsung",
        availability: "có",
        description: "SM-R800 có thiết kế cổ điển sang trọng, thời lượng pin ấn tượng và khả năng kết nối vượt trội cho bạn trải nghiệm liền mạch đỉnh cao.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/SamSung_SM_R810.jpg",
        linkproduct: "dong_ho_samsung_sm_r810",
        productname: "Đồng hồ thông minh SamSung SM-R810",
        saleoff: "-10%",
        price: 3600000,
        oldprice: 4000000,
        cat: "Đồng hồ",
        producer: "samsung",
        availability: "có",
        description: "Một chiếc đồng hồ thông minh có thể theo dõi vận động và theo dõi sức khỏe.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/Giay_Nam_Kamito.jpg",
        linkproduct: "giay_nam_kamito",
        productname: "Giày Nam Kamito",
        saleoff: "-10%",
        price: 360000,
        oldprice: 400000,
        cat: "Giày",
        producer: "manzo",
        availability: "có",
        description: "Với chất liệu da mềm mại, thật chân, phom giày hoàn toàn phù hợp với bàn chân người Việt.",
        gender: "nam"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e94",
        imagePath: "/img/Giay_Nam_Nau.jpg",
        linkproduct: "giay_nam_mau_nau",
        productname: "Giày Nam màu nâu",
        saleoff: "-20%",
        price: 320000,
        oldprice: 400000,
        cat: "Giày",
        producer: "manzo",
        availability: "có",
        description: "Với chất liệu vãi mềm mại, màu nâu sang trọng là một lựa chọn tốt.",
        gender: "nam"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Giay_Nike_Nam.jpg",
        linkproduct: "giay_nike_nam",
        productname: "Giày Nike Nam màu đen",
        saleoff: "-20%",
        price: 320000,
        oldprice: 400000,
        cat: "Giày",
        producer: "manzo",
        availability: "có",
        description: "Với chất liệu vãi mềm mại, đế chân cao, form vừa với bàn chân Việt.",
        gender: "nam"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Giay_Tay_Den.jpg",
        linkproduct: "giay_tay_den",
        productname: "Giày Tây Nam màu đen",
        saleoff: "-10%",
        price: 720000,
        oldprice: 800000,
        cat: "Giày",
        producer: "manzo",
        availability: "có",
        description: "Với chất liệu da mềm mại, màu đen huyền bí tạo nên vẽ lịch lãm cho đàn ông.",
        gender: "nam"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Boost_Nu_LATTE.jpg",
        linkproduct: "boost_nu_latte",
        productname: "Boost Nữ LATTE",
        saleoff: "-20%",
        price: 640000,
        oldprice: 800000,
        cat: "Giày",
        producer: "slimheel",
        availability: "có",
        description: "Với chất liệu da báo mềm mại, màu sắc quyến rũ, thu hút mọi ánh nhìn.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Giay_Nu_EGO.jpg",
        linkproduct: "giay_nu_ego",
        productname: "Giày Nữ EGO",
        saleoff: "-10%",
        price: 540000,
        oldprice: 600000,
        cat: "Giày",
        producer: "slimheel",
        availability: "có",
        description: "Kích thước 7 phân, màu sáng, ôm sát chân, là sự lựa chọn thông minh của phái nữ.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Giay_Nu_Slim Heel.jpg",
        linkproduct: "giay_nu_slimheel",
        productname: "Giày Nữ Slim Heel màu đỏ",
        saleoff: "-20%",
        price: 480000,
        oldprice: 600000,
        cat: "Giày",
        producer: "slimheel",
        availability: "có",
        description: "Giày có thiết kế sang trọng, phù hợp với các bộ dạ hội kiêu sa.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Giay_Nu_Zapatos.jpg",
        linkproduct: "giay_nu_zapatos",
        productname: "Giày Nữ ZAPATOS",
        saleoff: "-10%",
        price: 450000,
        oldprice: 500000,
        cat: "Giày",
        producer: "slimheel",
        availability: "có",
        description: "Giày có thiết kế thoải mái, thoáng mát nhưng không kém sang trọng. Phù hợp cho giới trẻ hiện nay.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Sandals_Chopin.jpg",
        linkproduct: "sandals_chopin",
        productname: "Sandals Chopin Nữ",
        saleoff: "-20%",
        price: 400000,
        oldprice: 500000,
        cat: "Giày",
        producer: "slimheel",
        availability: "có",
        description: "Sandals nhỏ nhắn, xinh xắn phù hợp cho các trang phục giản dị.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Tui_Nam_Babolat.png",
        linkproduct: "tui_nam_babolat",
        productname: "Túi Nam Babolat",
        saleoff: "-10%",
        price: 300000,
        oldprice: 400000,
        cat: "Cặp",
        producer: "manzo",
        availability: "có",
        description: "Chất liệu mềm mại, thiết kế 3 ngăn đủ đựng lượng lớn vật dụng.",
        gender: "nam"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Tui_Nam_VCAM.jpg",
        linkproduct: "tui_nam_vcam",
        productname: "Túi Nam VCAM",
        saleoff: "-10%",
        price: 500000,
        oldprice: 600000,
        cat: "Cặp",
        producer: "manzo",
        availability: "có",
        description: "Chất liệu mềm mại, thiết kế sang trọng, màu sắc sinh động, phù hợp cho các sự kiện lớn.",
        gender: "nam"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e95",
        imagePath: "/img/Tui_Nam_Wilson.jpg",
        linkproduct: "tui_nam_wilson",
        productname: "Túi Nam WILSON",
        saleoff: "-10%",
        price: 400000,
        oldprice: 500000,
        cat: "Cặp",
        producer: "manzo",
        availability: "có",
        description: "Chất liệu mềm mại, thiết kế nhiều ngăn, phù hợp cho các bạn sinh viên.",
        gender: "nam"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Tui_Nu_KM01.jpg",
        linkproduct: "tui_nu_km01",
        productname: "Túi Nữ KM01 màu đen",
        saleoff: "-10%",
        price: 400000,
        oldprice: 500000,
        cat: "Cặp",
        producer: "vanoca",
        availability: "có",
        description: "Chất liệu da, thiết kế nhỏ nhắn phù hợp các bạn nữ trẻ trung, nhí nhảnh.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Tui_Nu_KM22.jpg",
        linkproduct: "tui_nu_km22",
        productname: "Túi Nữ KM22 màu đen",
        saleoff: "-10%",
        price: 300000,
        oldprice: 400000,
        cat: "Cặp",
        producer: "vanoca",
        availability: "có",
        description: "Chất liệu da, màu đen huyền bí, thiết kế 2 ngăn phù hợp cho các nữ sinh mang đến trường học.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Tui_Nu_TR10.jpg",
        linkproduct: "tui_nu_tr10",
        productname: "Túi Nữ TR10 màu đen",
        saleoff: "-10%",
        price: 495000,
        oldprice: 550000,
        cat: "Cặp",
        producer: "vanoca",
        availability: "có",
        description: "Chất liệu da, màu đen huyền bí, thiết kế 1 ngăn, nhỏ nhắn, xinh xắn, phù hợp với các bạn nữ duyên dáng, dịu dàng.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Tui_Nu_TT17.jpg",
        linkproduct: "tui_nu_tt17",
        productname: "Túi Nữ TT17",
        saleoff: "-20%",
        price: 440000,
        oldprice: 550000,
        cat: "Cặp",
        producer: "vanoca",
        availability: "có",
        description: "Chất liệu mềm mại, nhiều màu sắc cho sự lựa chọn, thiết kế 1 ngăn, nhỏ nhắn, xinh xắn cùng với cái nơ xinh xinh.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Vi_Nam_Bogesi.jpg",
        linkproduct: "vi_nam_bogesi",
        productname: "Ví Nam Bogesi",
        saleoff: "-10%",
        price: 600000,
        oldprice: 700000,
        cat: "Ví",
        producer: "manzo",
        availability: "có",
        description: "Chất liệu da mềm mại, thiết kế vừa lòng bàn tay, cầm nắm tạo nên sự sang trọng cho nam giới.",
        gender: "nam",
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Vi_Nam_Ginals.jpg",
        linkproduct: "vi_nam_ginals",
        productname: "Ví Nam Ginals",
        saleoff: "-20%",
        price: 560000,
        oldprice: 700000,
        cat: "Ví",
        producer: "manzo",
        availability: "có",
        description: "Chất liệu da mềm mại, thiết kế nhiều ngăn có thể chứa nhiều loại giấy tờ quan trọng.",
        gender: "nam"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Vi_Nu_HC11.jpg",
        linkproduct: "vi_nu_hc11",
        productname: "Ví Nữ HC11",
        saleoff: "-10%",
        price: 800000,
        oldprice: 900000,
        cat: "Ví",
        producer: "vanoca",
        availability: "có",
        description: "Thiết kế quả cầu nhỏ nhắn. màu sắc sang trọng, sinh động, tạo sự quý phái, kiêu sa trong các tiệc dạ hội.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Vi_Nu_KM11.jpg",
        linkproduct: "vi_nu_km11",
        productname: "Ví Nữ KM11",
        saleoff: "-10%",
        price: 700000,
        oldprice: 800000,
        cat: "Ví",
        producer: "vanoca",
        availability: "có",
        description: "Thiết kế quả cầu nhỏ nhắn. màu sắc sang trọng, sinh động, phù hợp khi mặc váy đầm.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Vi_Nu_TK22.jpg",
        linkproduct: "vi_nu_tk22",
        productname: "Ví Nữ TK22",
        saleoff: "-10%",
        price: 700000,
        oldprice: 800000,
        cat: "Ví",
        producer: "vanoca",
        availability: "có",
        description: "Kết hợp 2 màu sắc, tạo điểm nhấn ở nút gài, sản phẩm sang trọng.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Vi_Nu_TR11.jpg",
        linkproduct: "vi_nu_tr11",
        productname: "Ví Nữ TR11",
        saleoff: "-20%",
        price: 640000,
        oldprice: 800000,
        cat: "Ví",
        producer: "vanoca",
        availability: "có",
        description: "Thiết kế nhỏ nhắn, màu đen huyền bí, có quai chéo, phù hợp với mọi cô nàng.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Vi_Nu_TT08.jpg",
        linkproduct: "vi_nu_tt08",
        productname: "Ví Nữ TT08",
        saleoff: "-20%",
        price: 720000,
        oldprice: 900000,
        cat: "Ví",
        producer: "vanoca",
        availability: "có",
        description: "Thiết kế đẹp mắt, chất liệu nỉ mềm mại, phù hợp các trang phục nữ tính, tạo sự kiêu sa cho phái đẹp.",
        gender: "nữ"
    }),
    new Product({
        IDSTall:"5e12178b6fbe5b1648551e96",
        imagePath: "/img/Vi_Nu_VT04.jpg",
        linkproduct: "vi_nu_vt04",
        productname: "Ví Nữ VT04",
        saleoff: "-20%",
        price: 720000,
        oldprice: 900000,
        cat: "Ví",
        producer: "vanoca",
        availability: "có",
        description: "Thiết kế nhỏ nhắn, vừa lòng bàn tay, dễ cầm nắm, tạo sự thoải mái khi dùng.",
        gender: "nữ"
    }),
]

var done = 0;

for(var i=0; i< products.length; i++){
    products[i].save((err, result)=>{
        done++;
        if(done === products.length){
            mongoose.disconnect();
        }

    })
};